name = "Coder"
license = "MIT"
licenselink = "https://github.com/luizdepra/hugo-coder/blob/master/LICENSE.md"
description = "A simple and clean blog theme for Hugo"
homepage = "https://github.com/luizdepra/hugo-coder/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.79.0"

[author]
name = "Luiz F. A. de Prá"
homepage = "https://luizdepra.com"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
